# Generated by Django 4.0.6 on 2022-07-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coworkermodel',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
