# Generated by Django 4.0.6 on 2022-07-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workedhours",
            options={},
        ),
        migrations.RenameField(
            model_name="workedhours",
            old_name="worker",
            new_name="worker_id",
        ),
    ]
