# Generated by Django 4.0.6 on 2022-07-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_workedhours_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workedhours",
            options={"verbose_name": "Hora", "verbose_name_plural": "Horas"},
        ),
        migrations.RenameField(
            model_name="workedhours",
            old_name="worker_id",
            new_name="worker_id_id",
        ),
    ]
